# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f006e6d16bf9336e9beff6ff3f0d383c0315393afdb1a191925375c4fa1c31d7923d4e2d618997438d5864bec936d0a4d494a07d7fd9f364c024a514f6a4b5

test:
  secret_key_base: d9b0334ae0095518ef6d364ff989104c4f09ad9b61cc16507c44eacb90dacf3ea36e9951d50cc943c1dfdb1435e04877b682b60a54e165a5387708495f1eef4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
